allowBuilds:
  electron-winstaller: true
minimumReleaseAgeExclude:
  - shell-quote@1.10.0
  - '@hono/node-server@2.0.10'
  - brace-expansion@5.0.8
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
overrides:
  '@hono/node-server': 2.0.10
  brace-expansion: 5.0.8
  shell-quote: 1.10.0
